### ISSUE TITLE
Cant compile thw windows version

### ISSUE THREAD

**Issue by ApexLead** [GiacomoLaw/Keylogger#59]
Hey,
I'm quiet new to compiling and I'm having trouble with it. 
I tried adding it to a new solution as is, changing its name to main.cpp and what not, but nothing works.
I keep getting compiling errors and don't know what to do, please help.

Error examples:
Error (active)	E0167	argument of type "const char *" is incompatible with parameter of type "char *"

Error (active)	E0167	argument of type "const char *" is incompatible with parameter of type "LPCWSTR"

Error	C1010	unexpected end of file while looking for precompiled header. Did you forget to add '#include "pch.h"' to your source?

Thanks in advance :)

**Comment by dairyxox** [comment]
I had this issue too. Trying to compile using Visual Studio 2017.
My solution was to "hard code" the output filename inside the save function, instead of passing it as a variable. In this simple form the program does not really need the filename to be a variable.

**Comment by FlameOfIgnis** [comment]
Im guessing you are talking about the errors in the image below. 
![errors](https://user-images.githubusercontent.com/16636092/47888963-69e67780-de58-11e8-9534-b5fb301c4fe9.JPG)

VScode is compiling this without a problem, but i know visual studio is sometimes needy.
You can just change constant strings like "Failed to install hook!" to L"Failed to install hook!", and it should work well. It is caused because there are char* strings passed, where Long pointers to wide char arrays (LPCWSTR) are needed.

**Comment by GiacomoLaw** [comment]
@FlameOfIgnis Thanks for the update. Do you think this should be fixed or not?

Thanks

**Comment by kumarutkarsh1** [comment]
53	38	C:\Users\Utkarsh\Downloads\Keylogger\Keylogger-master\Keylogger-master\windows\klog_main.cpp	[Error] cannot convert 'LPCWSTR {aka const wchar_t*}' to 'LPCSTR {aka const char*}' for argument '2' to 'int MessageBoxA(HWND, LPCSTR, LPCSTR, UINT)' it is showing this error and not compiling
